In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('casos_covid_2020.csv')

In [16]:
df.head()

,date,state,city,place_type,confirmed,deaths,order_for_place,is_last,estimated_population_2019,city_ibge_code,confirmed_per_100k_inhabitants,death_rate
0,2020-08-28,AP,NaN,state,42625,657,161,True,845731.0,16.0,5040.01863,0.0154
1,2020-08-27,AP,NaN,state,42285,652,160,False,845731.0,16.0,4999.81673,0.0154
2,2020-08-26,AP,NaN,state,41981,647,159,False,845731.0,16.0,4963.87149,0.0154
3,2020-08-25,AP,NaN,state,41553,642,158,False,845731.0,16.0,4913.26438,0.0155
4,2020-08-24,AP,NaN,state,41254,637,157,False,845731.0,16.0,4877.91035,0.0154

In [17]:
df_uf = df[df['place_type'] == 'state']

In [18]:
df_uf

,date,state,city,place_type,confirmed,deaths,order_for_place,is_last,estimated_population_2019,city_ibge_code,confirmed_per_100k_inhabitants,death_rate
0,2020-08-28,AP,NaN,state,42625,657,161,True,845731.0,16.0,5040.01863,0.0154
1,2020-08-27,AP,NaN,state,42285,652,160,False,845731.0,16.0,4999.81673,0.0154
2,2020-08-26,AP,NaN,state,41981,647,159,False,845731.0,16.0,4963.87149,0.0154
3,2020-08-25,AP,NaN,state,41553,642,158,False,845731.0,16.0,4913.26438,0.0155
4,2020-08-24,AP,NaN,state,41254,637,157,False,845731.0,16.0,4877.91035,0.0154
5,2020-08-23,AP,NaN,state,41120,631,156,False,845731.0,16.0,4862.06607,0.0153
6,2020-08-22,AP,NaN,state,41031,630,155,False,845731.0,16.0,4851.54263,0.0154
7,2020-08-21,AP,NaN,state,40875,627,154,False,845731.0,16.0,4833.09705,0.0153
8,2020-08-20,AP,NaN,state,40603,626,153,False,845731.0,16.0,4800.93552,0.0154
9,2020-08-19,AP,NaN,state,40211,622,152,False,845731.0,16.0,4754.58509,0.0155
10,2020-08-18,AP,NaN,state,39957,619,151,False,845731.0,16.0,4724.55190,0.0155
11,2020-08-17,AP,NaN,state,39703,617,150,False,845731.0,16.0,4694.51871,0.0155
12,2020-08-16,AP,NaN,state,39518,613,149,False,845731.0,16.0,4672.64414,0.0155
13,2020-08-15,AP,NaN,state,39431,613,148,False,845731.0,16.0,4662.35718,0.0155
14,2020-08-14,AP,NaN,state,39244,612,147,False,845731.0,16.0,4640.24613,0.0156
15,2020-08-13,AP,NaN,state,39015,609,146,False,845731.0,16.0,4613.16896,0.0156
16,2020-08-12,AP,NaN,state,38801,606,145,False,845731.0,16.0,4587.86541,0.0156
17,2020-08-11,AP,NaN,state,38636,604,144,False,845731.0,16.0,4568.35566,0.0156
18,2020-08-10,AP,NaN,state,38399,603,143,False,845731.0,16.0,4540.33256,0.0157
19,2020-08-09,AP,NaN,state,38208,602,142,False,845731.0,16.0,4517.74855,0.0158
20,2020-08-08,AP,NaN,state,38139,601,141,False,845731.0,16.0,4509.58993,0.0158
21,2020-08-07,AP,NaN,state,37964,599,140,False,845731.0,16.0,4488.89777,0.0158
22,2020-08-06,AP,NaN,state,37735,594,139,False,845731.0,16.0,4461.82060,0.0157
23,2020-08-05,AP,NaN,state,37318,588,138,False,845731.0,16.0,4412.51414,0.0158
24,2020-08-04,AP,NaN,state,36999,581,137,False,845731.0,16.0,4374.79530,0.0157
25,2020-08-03,AP,NaN,state,36804,576,136,False,845731.0,16.0,4351.73832,0.0157
26,2020-08-02,AP,NaN,state,36639,571,135,False,845731.0,16.0,4332.22857,0.0156
27,2020-08-01,AP,NaN,state,36595,568,134,False,845731.0,16.0,4327.02597,0.0155
28,2020-07-31,AP,NaN,state,36468,565,133,False,845731.0,16.0,4312.00937,0.0155
29,2020-07-30,AP,NaN,state,36272,561,132,False,845731.0,16.0,4288.83416,0.0155
...,...,...,...,...,...,...,...,...,...,...,...,...
520173,2020-03-27,SP,NaN,state,1223,68,30,False,45919049.0,35.0,2.66338,0.0556
520174,2020-03-26,SP,NaN,state,1052,58,29,False,45919049.0,35.0,2.29099,0.0551
520175,2020-03-25,SP,NaN,state,862,48,28,False,45919049.0,35.0,1.87722,0.0557
520176,2020-03-24,SP,NaN,state,810,40,27,False,45919049.0,35.0,1.76397,0.0494
520177,2020-03-23,SP,NaN,state,745,30,26,False,45919049.0,35.0,1.62242,0.0403
520178,2020-03-22,SP,NaN,state,631,22,25,False,45919049.0,35.0,1.37416,0.0349
520179,2020-03-21,SP,NaN,state,396,15,24,False,45919049.0,35.0,0.86239,0.0379
520180,2020-03-20,SP,NaN,state,396,9,23,False,45919049.0,35.0,0.86239,0.0227
520181,2020-03-19,SP,NaN,state,286,5,22,False,45919049.0,35.0,0.62284,0.0175
520182,2020-03-18,SP,NaN,state,240,3,21,False,45919049.0,35.0,0.52266,0.0125
520183,2020-03-17,SP,NaN,state,164,1,20,False,45919049.0,35.0,0.35715,0.0061
520184,2020-03-16,SP,NaN,state,152,0,19,False,45919049.0,35.0,0.33102,0.0000
520185,2020-03-14,SP,NaN,state,65,0,18,False,45919049.0,35.0,0.14155,0.0000
520186,2020-03-12,SP,NaN,state,46,0,17,False,45919049.0,35.0,0.10018,0.0000
520187,2020-03-11,SP,NaN,state,30,0,16,False,45919049.0,35.0,0.06533,0.0000
520188,2020-03-10,SP,NaN,state,19,0,15,False,45919049.0,35.0,0.04138,0.0000
520189,2020-03-09,SP,NaN,state,16,0,14,False,45919049.0,35.0,0.03484,0.0000
520190,2020-03-08,SP,NaN,state,16,0,13,False,45919049.0,35.0,0.03484,0.0000
520191,2020-03-07,SP,NaN,state,13,0,12,False,45919049.0,35.0,0.02831,0.0000
520192,2020-03-06,SP,NaN,state,10,0,11,False,45919049.0,35.0,0.02178,0.0000
520193,2020-03-05,SP,NaN,state,6,0,10,False,45919049.0,35.0,0.01307,0.0000
520194,2020-03-04,SP,NaN,state,3,0,9,False,45919049.0,35.0,0.00653,0.0000
520195,2020-03-03,SP,NaN,state,2,0,8,False,45919049.0,35.0,0.00436,0.0000
520196,2020-03-02,SP,NaN,state,2,0,7,False,45919049.0,35.0,0.00436,0.0000
520197,2020-03-01,SP,NaN,state,2,0,6,False,45919049.0,35.0,0.00436,0.0000
520198,2020-02-29,SP,NaN,state,2,0,5,False,45919049.0,35.0,0.00436,0.0000
520199,2020-02-28,SP,NaN,state,2,0,4,False,45919049.0,35.0,0.00436,0.0000
520200,2020-02-27,SP,NaN,state,1,0,3,False,45919049.0,35.0,0.00218,0.0000
520201,2020-02-26,SP,NaN,state,1,0,2,False,45919049.0,35.0,0.00218,0.0000
520202,2020-02-25,SP,NaN,state,1,0,1,False,45919049.0,35.0,0.00218,0.0000

In [28]:
df_uf_atual = df[(df['place_type'] == 'state') & (df['date'] == '2020-08-27')]

In [29]:
df_uf_atual

,date,state,city,place_type,confirmed,deaths,order_for_place,is_last,estimated_population_2019,city_ibge_code,confirmed_per_100k_inhabitants,death_rate
1,2020-08-27,AP,NaN,state,42285,652,160,False,845731.0,16.0,4999.81673,0.0154
2205,2020-08-27,AC,NaN,state,24269,607,164,False,881935.0,12.0,2751.79010,0.0250
4975,2020-08-27,AM,NaN,state,118083,3616,164,False,4144597.0,13.0,2849.08279,0.0306
13234,2020-08-27,DF,NaN,state,156863,2425,173,False,3015268.0,53.0,5202.29048,0.0155
13738,2020-08-27,AL,NaN,state,77755,1853,170,False,3337357.0,27.0,2329.83765,0.0238
25948,2020-08-27,ES,NaN,state,108662,3105,175,False,4018650.0,32.0,2703.94287,0.0286
36426,2020-08-27,CE,NaN,state,211053,8374,165,False,9132078.0,23.0,2311.11692,0.0397
60619,2020-08-27,GO,NaN,state,128241,2987,169,False,7018354.0,52.0,1827.22331,0.0233
84593,2020-08-27,MS,NaN,state,47152,823,167,True,2778986.0,50.0,1696.73399,0.0175
92355,2020-08-27,BA,NaN,state,247853,5178,173,False,14873064.0,29.0,1666.45555,0.0209
136429,2020-08-27,MA,NaN,state,148923,3402,161,False,7075181.0,21.0,2104.86488,0.0228
162449,2020-08-27,MT,NaN,state,88385,2707,158,False,3484466.0,51.0,2536.54362,0.0306
174363,2020-08-27,PA,NaN,state,196874,6106,163,False,8602865.0,15.0,2288.47018,0.0310
192604,2020-08-27,PB,NaN,state,104096,2388,169,False,4018127.0,25.0,2590.65978,0.0229
216599,2020-08-27,PE,NaN,state,122147,7480,169,False,9557071.0,26.0,1278.07986,0.0612
240289,2020-08-27,PI,NaN,state,76033,1785,161,False,3273227.0,22.0,2322.87587,0.0235
263158,2020-08-27,RJ,NaN,state,219198,15859,167,True,17264943.0,33.0,1269.61323,0.0724
276249,2020-08-27,MG,NaN,state,205942,5049,172,False,21168791.0,31.0,972.85669,0.0245
351679,2020-08-27,RO,NaN,state,53805,1109,153,False,1777225.0,11.0,3027.47260,0.0206
357319,2020-08-27,RR,NaN,state,42997,587,157,True,605761.0,14.0,7098.01390,0.0137
359500,2020-08-27,RN,NaN,state,61416,2240,152,True,3506853.0,24.0,1751.31378,0.0365
375429,2020-08-27,PR,NaN,state,124074,3153,167,False,11433957.0,41.0,1085.13614,0.0254
416473,2020-08-27,SE,NaN,state,71599,1830,156,False,2298696.0,28.0,3114.76594,0.0256
425101,2020-08-27,SC,NaN,state,139638,2170,169,False,7164788.0,42.0,1948.94811,0.0155
458378,2020-08-27,TO,NaN,state,48580,649,159,True,1572866.0,17.0,3088.62929,0.0134
472051,2020-08-27,RS,NaN,state,118315,3275,168,False,11377239.0,43.0,1039.92717,0.0277
520020,2020-08-27,SP,NaN,state,784453,29415,183,False,45919049.0,35.0,1708.33895,0.0375

In [30]:
df_uf_atual['deaths'].sum()

118824

Atividades para casa
=====
Criar os seguintes dataframes:

1. Para testar filtros
 - Histórico de casos em Santa Rita do Sapucaí
 - Histórico de casos de todas as cidades de MG
 - Registro do dia 27 de todas as cidades de São Paulo
 - Registro do dia 27 de todas as cidades do Brasil
 
 
2. Retornar os seguintes dados (para o dia 27):
 - Total de casos por estado
 - Total de casos por cidade
 - Total de mortes por estado
 - Total de mortes por cidade


3. Próxima aula
 - Ordenar dados
 - Agrupar (Qual o total de mortes no BRASIL por dia)
 - Transformar/aplicar
 - ...